task_type: detection
dataset_category: coco
calibration_dataset:
  num_classes: null
  num_frames: 10
  name: modelmaker
  path: /opt/EdgeAIRoot/4878386/projects/ad25e250/dataset
  split: train
  shuffle: true
  dataset_info: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/dataset.yaml
input_dataset:
  num_classes: null
  num_frames: 30
  name: modelmaker
  path: /opt/EdgeAIRoot/4878386/projects/ad25e250/dataset
  split: val
  shuffle: false
  dataset_info: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/dataset.yaml
preprocess:
  resize: 416
  crop: 416
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  add_flip_image: false
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  work_dir: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work
  target_machine: pc
  target_device: AM68A
  run_suffix: null
  tidl_offload: true
  input_optimization: true
  input_data_layout: NCHW
  input_mean: null
  input_scale: null
  run_dir_tree_depth: 3
  runtime_options:
    platform: J7
    version: 9.1.0
    tidl_tools_path: /opt/edgeai-benchmark/tools/AM68A/tidl_tools
    artifacts_folder: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/artifacts
    tensor_bits: 8
    import: 'yes'
    accuracy_level: 1
    debug_level: 0
    inference_mode: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 5
    advanced_options:calibration_iterations: 5
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: /multi_level_conv_obj.2/Conv_output_0,
      /multi_level_conv_reg.2/Conv_output_0, /multi_level_conv_cls.2/Conv_output_0,
      /multi_level_conv_obj.1/Conv_output_0, /multi_level_conv_reg.1/Conv_output_0,
      /multi_level_conv_cls.1/Conv_output_0, /multi_level_conv_obj.0/Conv_output_0,
      /multi_level_conv_reg.0/Conv_output_0, /multi_level_conv_cls.0/Conv_output_0
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    ti_internal_nc_flag: 83886080
    object_detection:confidence_threshold: 0.6
    object_detection:top_k: 200
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/model/model.prototxt
    advanced_options:quant_params_proto_path: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/model/model_qparams.prototxt
  model_path: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/training/model.onnx
  tidl_tools_path: /opt/edgeai-benchmark/tools/AM68A/tidl_tools
  run_dir: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200
  num_tidl_subgraphs: 16
  model_id: od-8200
  model_type: null
  input_details:
  - name: inputNet_IN
    shape:
    - 1
    - 3
    - 416
    - 416
    type: tensor(uint8)
  output_details:
  - name: dets
    shape:
    - 1
    - 1
    - 1
    - 1
    - 200
    - 5
    type: tensor(float)
  - name: labels
    shape:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 200
    type: tensor(int64)
  num_inputs: 1
  extra_inputs: null
  tensor_bits: 8
  quant_params_proto_path: true
  supported_machines: null
  with_onnxsim: false
  shape_inference: true
  artifacts_folder: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/artifacts
  model_folder: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/model
  model_file: /opt/EdgeAIRoot/4878386/projects/ad25e250/run/20240611-035238/yolox_nano_lite/compilation/AM68A/work/od-8200/model/model.onnx
postprocess:
  detection_threshold: 0.6
  save_output: true
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
metric:
  label_offset_pred: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: null
  model_shortlist: 10
